server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ticketsMicroservice
    username: root
    password: Pa$$w0rd
    driver: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: