server:
  port: 8091

spring:
  application:
    name: message-service


management:
  endpoints:
    web:
      exposure:
        include: prometheus

msvc:
  queue:
    name: cola1


eureka:
  client:
    service-url:
      defaultZone: http://eureka:password@localhost:8761/eureka