server:
  port: 8083

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: sales-service

  application:
    name: SALES-SERVICE

eureka:
  instance:
    prefer-ip-addres: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka